# Generated by Django 4.1.5 on 2023-09-16 02:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Caissiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("numero_telephone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="ConsultationDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "prix",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DettePatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_patient", models.CharField(max_length=100)),
                ("prenom_patient", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=20)),
                (
                    "montant",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ExamenDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=30)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="LaserDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "prix",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedecinOphalmo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("specialite", models.CharField(max_length=200)),
                ("numero_telephone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="ModePaiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="OperationDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "prix",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                (
                    "sexe",
                    models.CharField(
                        choices=[
                            ("homme", "Homme"),
                            ("femme", "Femme"),
                            ("autres", "Autres"),
                        ],
                        max_length=6,
                    ),
                ),
                ("numero_dossier", models.CharField(max_length=15)),
                (
                    "date_de_naissance",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("profession", models.CharField(max_length=25)),
                ("adresse", models.CharField(max_length=25)),
                ("telephone", models.CharField(max_length=15)),
                (
                    "assurance",
                    models.CharField(
                        choices=[("oui", "Oui"), ("non", "Non")], max_length=3
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="PiqureDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Rendez_vous_en_ligne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=30)),
                ("prenom", models.CharField(max_length=30)),
                ("adresse", models.CharField(max_length=70)),
                ("telephone", models.CharField(max_length=15)),
                ("objet", models.CharField(max_length=100)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Rendez_vous_local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=30)),
                ("prenom", models.CharField(max_length=30)),
                ("telephone", models.CharField(max_length=15)),
                (
                    "objet",
                    models.CharField(
                        choices=[
                            ("laser", "Laser"),
                            ("consultation", "Consultation"),
                            ("examen", "Examen"),
                            ("operation", "Operation"),
                            ("lunette", "Lunette"),
                            ("piqure", "Piqure"),
                        ],
                        max_length=25,
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="SalleDAttente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=25)),
                ("prenom", models.CharField(max_length=25)),
                ("numero_dossier", models.CharField(max_length=8)),
                (
                    "heure_arrivee",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "traitement",
                    models.CharField(
                        choices=[
                            ("laser", "Laser"),
                            ("consultation", "Consultation"),
                            ("examen", "Examen"),
                            ("operation", "Operation"),
                            ("lunette", "Lunette"),
                            ("piqure", "Piqure"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TypePiqure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("cylindre_os", models.FloatField()),
                ("cylindre_od", models.FloatField()),
                ("sphere_od", models.FloatField()),
                ("sphere_os", models.FloatField()),
                ("axe_od", models.IntegerField()),
                ("axe_os", models.IntegerField()),
                ("tension_od", models.FloatField()),
                ("tension_os", models.FloatField()),
                ("vision_os", models.CharField(max_length=100)),
                ("vision_od", models.CharField(max_length=100)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.salledattente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Piqure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("detail", models.TextField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.salledattente",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.typepiqure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("detail", models.TextField()),
                (
                    "Medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.medecinophalmo",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.salledattente",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.typeoperation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Laser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("information", models.TextField()),
                (
                    "Medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.medecinophalmo",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.salledattente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacturePiqure",
            fields=[
                (
                    "facturepiqure_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("nom_patient", models.CharField(max_length=100)),
                ("prenom_patient", models.CharField(max_length=100)),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("special", models.BooleanField(default=False)),
                (
                    "prix",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "caissiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.caissiere",
                    ),
                ),
                (
                    "mode_paiement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.modepaiement",
                    ),
                ),
                (
                    "piqure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.piquredetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FactureOperation",
            fields=[
                (
                    "factureoperation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("nom_patient", models.CharField(max_length=100)),
                ("prenom_patient", models.CharField(max_length=100)),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("special", models.BooleanField(default=False)),
                (
                    "prix",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "caissiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.caissiere",
                    ),
                ),
                (
                    "mode_paiement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.modepaiement",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.operationdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FactureLaser",
            fields=[
                (
                    "facturelaser_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("nom_patient", models.CharField(max_length=100)),
                ("prenom_patient", models.CharField(max_length=100)),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("special", models.BooleanField(default=False)),
                (
                    "prix",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "caissiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.caissiere",
                    ),
                ),
                (
                    "laser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.laserdetail",
                    ),
                ),
                (
                    "mode_paiement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.modepaiement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FactureExamen",
            fields=[
                (
                    "factureexamen_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("nom_patient", models.CharField(max_length=100)),
                ("prenom_patient", models.CharField(max_length=100)),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("special", models.BooleanField(default=False)),
                (
                    "prix",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "caissiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.caissiere",
                    ),
                ),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.examendetail",
                    ),
                ),
                (
                    "mode_paiement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.modepaiement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FactureConsultation",
            fields=[
                (
                    "factureconsultation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("nom_patient", models.CharField(max_length=100)),
                ("prenom_patient", models.CharField(max_length=100)),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("special", models.BooleanField(default=False)),
                (
                    "prix",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "Consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.consultationdetail",
                    ),
                ),
                (
                    "caissiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.caissiere",
                    ),
                ),
                (
                    "mode_paiement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.modepaiement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Examen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "resultat",
                    models.FileField(blank=True, null=True, upload_to="resultats/"),
                ),
                (
                    "nom_examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.examendetail",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.vision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("motif_consultation", models.CharField(max_length=50)),
                ("avis", models.CharField(max_length=250)),
                ("prescription", models.TextField(blank=True, null=True)),
                ("dosage", models.TextField(blank=True, null=True)),
                ("debut", models.DateTimeField(default=django.utils.timezone.now)),
                ("fin", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.medecinophalmo",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apphopital.vision",
                    ),
                ),
            ],
        ),
    ]
